// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

import type { DateTime, Interval } from './custom-types'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'fr'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Ticket report for {interval|subjectReportInterval}
	 * @param {Interval} interval
	 */
	subject: RequiredParams<'interval|subjectReportInterval'>
	/**
	 * Dear {name},
	 * @param {string} name
	 */
	greeting: RequiredParams<'name'>
	/**
	 * Here is a summary of jira ticket activity for {month|monthYear}
	 * @param {DateTime} month
	 */
	preamble: RequiredParams<'month|monthYear'>
	/**
	 * Ticket no.
	 */
	issueKey: string
	/**
	 * Summary
	 */
	issueSummary: string
	created: {
		/**
		 * Tickets created between {start|dtHeader} and {end|dtHeader}
		 * @param {DateTime} end
		 * @param {DateTime} start
		 */
		heading: RequiredParams<'end|dtHeader' | 'start|dtHeader'>
	}
	allTickets: {
		/**
		 * All open tickets
		 */
		heading: string
	}
	closed: {
		/**
		 * Tickets closed between {start|dtHeader} and {end|dtHeader}
		 * @param {DateTime} end
		 * @param {DateTime} start
		 */
		heading: RequiredParams<'end|dtHeader' | 'start|dtHeader'>
	}
}

export type TranslationFunctions = {
	/**
	 * Ticket report for {interval|subjectReportInterval}
	 */
	subject: (arg: { interval: Interval }) => LocalizedString
	/**
	 * Dear {name},
	 */
	greeting: (arg: { name: string }) => LocalizedString
	/**
	 * Here is a summary of jira ticket activity for {month|monthYear}
	 */
	preamble: (arg: { month: DateTime }) => LocalizedString
	/**
	 * Ticket no.
	 */
	issueKey: () => LocalizedString
	/**
	 * Summary
	 */
	issueSummary: () => LocalizedString
	created: {
		/**
		 * Tickets created between {start|dtHeader} and {end|dtHeader}
		 */
		heading: (arg: { end: DateTime, start: DateTime }) => LocalizedString
	}
	allTickets: {
		/**
		 * All open tickets
		 */
		heading: () => LocalizedString
	}
	closed: {
		/**
		 * Tickets closed between {start|dtHeader} and {end|dtHeader}
		 */
		heading: (arg: { end: DateTime, start: DateTime }) => LocalizedString
	}
}

export type Formatters = {
	dtHeader: (value: DateTime) => unknown
	monthYear: (value: DateTime) => unknown
	subjectReportInterval: (value: Interval) => unknown
}
