@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(entretienStaff, "Entretien Member")
System(gmail, Gmail)
System(jira, Jira)
System_Boundary("gcp", "Google Cloud Platform"){
  Container(gcloudsched, "Trigger", "Google Cloud Scheduler", "Publish trigger message")
  Container(announcer_gcf, "Announcer", "Cloud Function", "Generate Jira ticket reports")
  Container(mailer_gcf, "Mailer", "Cloud Function", "Mail report to addressee")
}

Rel(gcloudsched, announcer_gcf, "Trigger", "Pubsub")
Rel(announcer_gcf, jira, "Get all changes for report interval", "HTTP")
Rel(announcer_gcf, mailer_gcf, "Addressed report", "Pubsub")
Rel(mailer_gcf, gmail, "mail", "SMTP")
Rel(gmail, entretienStaff, "Notify")
@enduml
